In [2]:
import pandas as pd

path = "./datasets.CSV"

In [3]:
df = pd.read_csv(path, encoding='cp949');
df.head(5).T

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26408\3110332436.py:1: DtypeWarning: Columns (16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding='cp949');

                     0          1          2          3          4
공시연도              2026       2026       2026       2026       2026
기준연도              2026       2026       2026       2026       2026
학교코드              2749       2748       2748       2748       2748
학교명          가야대학교(고령)  가야대학교(김해)  가야대학교(김해)  가야대학교(김해)  가야대학교(김해)
본분교명             제2캠퍼스         본교         본교         본교         본교
대학구분                대학         대학         대학         대학         대학
학교종류               대학교        대학교        대학교        대학교        대학교
설립구분                사립         사립         사립         사립         사립
설립유형                사립         사립         사립         사립         사립
소재지유형             비수도권       비수도권       비수도권       비수도권       비수도권
지역                  경북         경남         경남         경남         경남
학교상태                기존         기존         기존         기존         기존
단과대학           단과대구분없음    단과대구분없음    단과대구분없음    단과대구분없음    단과대구분없음
학과코드            208646     208655     231464     236913     208656
학과명             자율전공학부       간호학과     경영물류학과     경찰소방학과     경찰행정학과
대학자체계열         인문ㆍ사회계열     자연과학계열    인문ㆍ사회계열    인문ㆍ사회계열    인문ㆍ사회계열
표준분류_대계열        인문사회계열     자연과학계열     인문사회계열     인문사회계열     인문사회계열
표준분류_중계열         N.C.E         간호      경영?경제       사회과학       사회과학
표준분류_소계열        N.C.E.        간호학     무역?유통학        행정학        행정학
주야간구분               주간         주간         주간         주간         주간
학과특성              일반과정       일반과정       일반과정       일반과정       일반과정
입학정원수                0        166          0          0          0
모집인원_계               0        186          0          0          0
모집인원_정원내             0        167          0          0          0
모집인원_정원외             0         19          0          0          0
지원자_계                0       1338          0          0          0
지원자_정원내              0       1255          0          0          0
지원자_정원외              0         83          0          0          0
입학자_계                0        185          0          0          0
입학자_정원내_남자           0         55          0          0          0
입학자_정원내_여자           0        112          0          0          0
입학자_정원외_남자           0          3          0          0          0
입학자_정원외_여자           0         15          0          0          0
정원내 신입생 충원율        0.0      100.0        0.0        0.0        0.0
경쟁률                0.0        7.5        0.0        0.0        0.0

In [4]:
print(df.isnull().sum())

공시연도               0
기준연도               0
학교코드               0
학교명                0
본분교명               0
대학구분               0
학교종류               0
설립구분               0
설립유형               0
소재지유형              0
지역                 0
학교상태               0
단과대학               0
학과코드               0
학과명                0
대학자체계열             0
표준분류_대계열       31814
표준분류_중계열       31814
표준분류_소계열       31814
주야간구분              0
학과특성               0
입학정원수              0
모집인원_계             0
모집인원_정원내           0
모집인원_정원외           0
지원자_계              0
지원자_정원내            0
지원자_정원외            0
입학자_계              0
입학자_정원내_남자         0
입학자_정원내_여자         0
입학자_정원외_남자         0
입학자_정원외_여자         0
정원내 신입생 충원율        0
경쟁률                0
dtype: int64

In [5]:
df[df["표준분류_대계열"].isnull()].head(5).T

              285340   285341   285342   285343    285344
공시연도            2012     2012     2012     2012      2012
기준연도            2012     2012     2012     2012      2012
학교코드              42       43       43       43        43
학교명            가야대학교    가야대학교    가야대학교    가야대학교     가야대학교
본분교명              본교    제2캠퍼스    제2캠퍼스    제2캠퍼스     제2캠퍼스
대학구분              대학       대학       대학       대학        대학
학교종류             대학교      대학교      대학교      대학교       대학교
설립구분              사립       사립       사립       사립        사립
설립유형              사립       사립       사립       사립        사립
소재지유형           비수도권     비수도권     비수도권     비수도권      비수도권
지역                경북       경남       경남       경남        경남
학교상태              기존       기존       기존       기존        기존
단과대학         단과대구분없음  단과대구분없음  단과대구분없음  단과대구분없음   단과대구분없음
학과코드             289     9801    10387    11616      1318
학과명           자율전공학부     간호학과   경찰행정학과     교양학부  도시토목환경학과
대학자체계열       인문ㆍ사회계열   자연과학계열  인문ㆍ사회계열  인문ㆍ사회계열      공학계열
표준분류_대계열         NaN      NaN      NaN      NaN       NaN
표준분류_중계열         NaN      NaN      NaN      NaN       NaN
표준분류_소계열         NaN      NaN      NaN      NaN       NaN
주야간구분             주간       주간       주간       주간        주간
학과특성            일반과정     일반과정     일반과정     일반과정      일반과정
입학정원수             36      124       55        0         0
모집인원_계            36      142       57        0         0
모집인원_정원내          36      124       55        0         0
모집인원_정원외           0       18        2        0         0
지원자_계             94     1313      367        0         0
지원자_정원내           94     1118      362        0         0
지원자_정원외            0      195        5        0         0
입학자_계             30      141       55        0         0
입학자_정원내_남자        27       26       32        0         0
입학자_정원내_여자         3       98       23        0         0
입학자_정원외_남자         0        0        0        0         0
입학자_정원외_여자         0       17        0        0         0
정원내 신입생 충원율   83.333    100.0    100.0      0.0       0.0
경쟁률              2.6      9.0      6.6      0.0       0.0

In [6]:
df[df["표준분류_대계열"].isnull()].tail(5).T

                317149     317150     317151     317152     317153
공시연도              2011       2011       2011       2011       2011
기준연도              2011       2011       2011       2011       2011
학교코드               333        333        333        333        333
학교명           화신사이버대학교   화신사이버대학교   화신사이버대학교   화신사이버대학교   화신사이버대학교
본분교명                본교         본교         본교         본교         본교
대학구분                대학         대학         대학         대학         대학
학교종류         사이버대학(대학)  사이버대학(대학)  사이버대학(대학)  사이버대학(대학)  사이버대학(대학)
설립구분                사립         사립         사립         사립         사립
설립유형                사립         사립         사립         사립         사립
소재지유형             비수도권       비수도권       비수도권       비수도권       비수도권
지역                  부산         부산         부산         부산         부산
학교상태                기존         기존         기존         기존         기존
단과대학           단과대구분없음    단과대구분없음    단과대구분없음    단과대구분없음    단과대구분없음
학과코드             44842      30243      26221      54626      48177
학과명            사회복지학전공    상담심리학전공     실용영어전공    실용일본어전공    한국어교육전공
대학자체계열         인문ㆍ사회계열    인문ㆍ사회계열    인문ㆍ사회계열    인문ㆍ사회계열    인문ㆍ사회계열
표준분류_대계열           NaN        NaN        NaN        NaN        NaN
표준분류_중계열           NaN        NaN        NaN        NaN        NaN
표준분류_소계열           NaN        NaN        NaN        NaN        NaN
주야간구분               원격         원격         원격         원격         원격
학과특성              일반과정       일반과정       일반과정       일반과정       일반과정
입학정원수                0          0          0          0          0
모집인원_계               0          0          0          0          0
모집인원_정원내             0          0          0          0          0
모집인원_정원외             0          0          0          0          0
지원자_계                0          0          0          0          0
지원자_정원내              0          0          0          0          0
지원자_정원외              0          0          0          0          0
입학자_계                0          0          0          0          0
입학자_정원내_남자           0          0          0          0          0
입학자_정원내_여자           0          0          0          0          0
입학자_정원외_남자           0          0          0          0          0
입학자_정원외_여자           0          0          0          0          0
정원내 신입생 충원율        0.0        0.0        0.0        0.0        0.0
경쟁률                0.0        0.0        0.0        0.0        0.0

In [7]:
df_recent = df[df['기준연도'].isin([2022, 2023, 2024, 2025, 2026])]
df_recent.head(5)

,공시연도,기준연도,학교코드,학교명,본분교명,대학구분,학교종류,설립구분,설립유형,소재지유형,...,지원자_계,지원자_정원내,지원자_정원외,입학자_계,입학자_정원내_남자,입학자_정원내_여자,입학자_정원외_남자,입학자_정원외_여자,정원내 신입생 충원율,경쟁률
0,2026,2026,2749,가야대학교(고령),제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
1,2026,2026,2748,가야대학교(김해),본교,대학,대학교,사립,사립,비수도권,...,1338,1255,83,185,55,112,3,15,100.0,7.5
2,2026,2026,2748,가야대학교(김해),본교,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
3,2026,2026,2748,가야대학교(김해),본교,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
4,2026,2026,2748,가야대학교(김해),본교,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0

In [8]:
df_recent.groupby("학교명")["모집인원_정원내"].sum()

학교명
가야대학교(고령)        0
가야대학교(김해)     2192
가천대학교        20399
가톨릭관동대학교      8470
가톨릭꽃동네대학교      547
             ...
호서대학교        14448
호원대학교         5356
홍익대학교        18625
화성의과학대학교      1358
화신사이버대학교      2702
Name: 모집인원_정원내, Length: 246, dtype: int64

In [9]:
# 본교와 학교명이 다른 이원화캠퍼스를 가진 대학교는 학습 데이터에서 제거
exclude_prefixes = (
    '가야대학교',
    '영산대학교',
    '목포대학교',
    '국립목포대학교',
    '창원대학교',
    '국립창원대학교',
    '강원대학교',
    '강릉원주대학교',
    '국립강릉원주대학교',
)

df_recent = df_recent[~df_recent['학교명'].str.startswith(exclude_prefixes, na=False)].copy()

In [10]:
df_recent[~df_recent['본분교명'].isin(['본교', '분교'])]

,공시연도,기준연도,학교코드,학교명,본분교명,대학구분,학교종류,설립구분,설립유형,소재지유형,...,지원자_계,지원자_정원내,지원자_정원외,입학자_계,입학자_정원내_남자,입학자_정원내_여자,입학자_정원외_남자,입학자_정원외_여자,정원내 신입생 충원율,경쟁률
796,2026,2026,48,가톨릭대학교,제2캠퍼스,대학,대학교,사립,사립,수도권,...,1024,973,51,82,16,64,0,2,100.0,12.2
797,2026,2026,48,가톨릭대학교,제2캠퍼스,대학,대학교,사립,사립,수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
798,2026,2026,48,가톨릭대학교,제2캠퍼스,대학,대학교,사립,사립,수도권,...,3006,2917,89,96,65,28,0,3,100.0,31.4
799,2026,2026,49,가톨릭대학교,제3캠퍼스,대학,대학교,사립,사립,수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
800,2026,2026,49,가톨릭대학교,제3캠퍼스,대학,대학교,사립,사립,수도권,...,95,93,2,52,29,21,2,0,100.0,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122542,2022,2022,2949,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122543,2022,2022,2949,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122544,2022,2022,2949,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122545,2022,2022,2949,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122546,2022,2022,2949,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0

In [11]:
# df2, 이원화캠퍼스가 존재하는 학교명 시리즈
df2 = df_recent[~df_recent['본분교명'].isin(['본교', '분교'])]["학교명"].drop_duplicates()
df2.head(5)

796      가톨릭대학교
2131      건양대학교
2468      경기대학교
2788      경동대학교
3808    경인교육대학교
Name: 학교명, dtype: object

In [12]:
# df3, 이원화캠퍼스, 분교를 제외한 본교의 데이터테이블
df3 = df_recent[df_recent["본분교명"] == "본교"]
print(df3.head(5))
print(df3.shape)

    공시연도  기준연도  학교코드    학교명 본분교명 대학구분 학교종류 설립구분 설립유형 소재지유형  ... 지원자_계 지원자_정원내  \
36  2026  2026    63  가천대학교   본교   대학  대학교   사립   사립   수도권  ...     0       0
37  2026  2026    63  가천대학교   본교   대학  대학교   사립   사립   수도권  ...     0       0
38  2026  2026    63  가천대학교   본교   대학  대학교   사립   사립   수도권  ...  6316    6085
39  2026  2026    63  가천대학교   본교   대학  대학교   사립   사립   수도권  ...     0       0
40  2026  2026    63  가천대학교   본교   대학  대학교   사립   사립   수도권  ...  6137    5900

   지원자_정원외  입학자_계 입학자_정원내_남자 입학자_정원내_여자 입학자_정원외_남자 입학자_정원외_여자 정원내 신입생 충원율  \
36       0      0          0          0          0          0         0.0
37       0      0          0          0          0          0         0.0
38     231    250         79        131          6         34       100.0
39       0      0          0          0          0          0         0.0
40     237    296         71        184          9         32       100.0

     경쟁률
36   0.0
37   0.0
38  29.0
39   0.0
40  23.1

[5 rows x 35 columns]
(108132, 35)

In [13]:
# df2에 해당하는 학교명을 가진 행의 학교명과 학교코드 열만 추출
# df4, 이게 본교 학교코드 데이터테이블
df4 = df3[df3["학교명"].isin(df2)][["학교명", "학교코드"]].drop_duplicates()
df4

            학교명  학교코드
648      가톨릭대학교    46
1997      건양대학교    54
2211      경기대학교    56
2726      경동대학교    60
3793    경인교육대학교   256
8507      단국대학교    82
12692     명지대학교   109
14126     상명대학교   117
18538     신한대학교  2712
18732     안양대학교   147
19748   예원예술대학교   218
20977     을지대학교   161
21304     인제대학교   164
21480  인천가톨릭대학교   168
21802     전남대학교    23
23394     중앙대학교   175
27934     홍익대학교   212

In [14]:
# 그러면 이제 df_recent에서 각 행의 학교명을 df4에 있는 학교명과 비교해서 일치하면
# 이원화캠퍼스(df2)의 학교코드를 df4의 학교코드로 덮어쓰기

df_recent[(df_recent["학교명"].isin(df4["학교명"])) & (~df_recent["본분교명"].isin(["본교", "분교"]))]["학교코드"]

796         48
797         48
798         48
799         49
800         49
          ...
122542    2949
122543    2949
122544    2949
122545    2949
122546    2949
Name: 학교코드, Length: 4930, dtype: int64

In [15]:
# df4는 학교명마다 학교코드가 하나씩 있어야 함
code_map = df4.set_index('학교명')['학교코드']

# 학교명에 해당하는 df4의 학교코드 조회
mapped_codes = df_recent['학교명'].map(code_map)

# 학교명이 일치하고, 분교가 아닌 행 선택
mask = mapped_codes.notna() & df_recent['본분교명'].ne('분교')

# 선택된 행의 학교코드를 덮어쓰기
df_recent.loc[mask, '학교코드'] = mapped_codes.loc[mask]
df_recent[df_recent["본분교명"] == "제2캠퍼스"]

,공시연도,기준연도,학교코드,학교명,본분교명,대학구분,학교종류,설립구분,설립유형,소재지유형,...,지원자_계,지원자_정원내,지원자_정원외,입학자_계,입학자_정원내_남자,입학자_정원내_여자,입학자_정원외_남자,입학자_정원외_여자,정원내 신입생 충원율,경쟁률
796,2026,2026,46,가톨릭대학교,제2캠퍼스,대학,대학교,사립,사립,수도권,...,1024,973,51,82,16,64,0,2,100.0,12.2
797,2026,2026,46,가톨릭대학교,제2캠퍼스,대학,대학교,사립,사립,수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
798,2026,2026,46,가톨릭대학교,제2캠퍼스,대학,대학교,사립,사립,수도권,...,3006,2917,89,96,65,28,0,3,100.0,31.4
2131,2026,2026,54,건양대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
2132,2026,2026,54,건양대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122542,2022,2022,212,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122543,2022,2022,212,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122544,2022,2022,212,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122545,2022,2022,212,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0
122546,2022,2022,212,홍익대학교,제2캠퍼스,대학,대학교,사립,사립,비수도권,...,0,0,0,0,0,0,0,0,0.0,0.0